id: I5E790444
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:17:08+00:00'
last_modified: '2022-06-10T08:58:04.963697+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10580
  title: ཆོས་བདག་བཀའ་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C8C8:
      image_group_id: I1KG10661
      title: ''
      total_pages: 282
      order: 1
      base_file: C8C8.txt
    21A4:
      image_group_id: I1KG10662
      title: ''
      total_pages: 314
      order: 2
      base_file: 21A4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
